---
version: '2'
services:
  news-elasticsearch:
    image: elasticsearch:7.6.2
    container_name: news-elasticsearch
    environment:
      - discovery.type=single-node
    volumes:
      - news_es_volume:/usr/share/elasticsearch
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - news-app
  news-webapp:
    container_name: news-webapp
    build:
      context: ../
      dockerfile: ./docker/news-browser-app/Dockerfile
    depends_on:
      - news-elasticsearch
    restart: "always"
    volumes:
      - /PATH/TO/DOCUMENTS/DIR:/home/data/documents
      - ./entrypoint.sh:/entrypoint.sh
    entrypoint: ["/entrypoint.sh", "/home/data/documents", "sample500000"]
    ports:
        - "15001:5001"
        - "15000:5000"
    networks:
      - news-app


volumes:
  news_es_volume:
  data_volume:

networks:
  news-app:
    driver: bridge
